Repository kakawait/hugo-tranquilpeak-theme, pull requests merged in 2018-08, with the labels that each got.

#284 dutch
  i18n/nl-nl.yaml
Labels: enhancement

#288 Allow mailto link as menu link
  layouts/partials/menu.html
Labels: enhancement

#290 Add showcases requests
  exampleSite/content/post/Who-is-using-Tranquilpeak-Hugo-Theme.md
Labels: showcase

#291 Remove urlize on display name
  exampleSite/content/post/Who-is-using-Tranquilpeak-Hugo-Theme.md
  layouts/taxonomy/category.terms.html
Labels: bug
