Repository kakawait/hugo-tranquilpeak-theme, pull requests merged in 2019-07, with the labels that each got.

#301 Make list template work for any content type
  layouts/_default/list.html
Labels: enhancement

#345 Add swedish translation
  i18n/sv-se.yaml
Labels: enhancement

#348 Add swedish translation
  i18n/sv-se.yaml
Labels: enhancement

#349 fix:warn when use 0.55.5
  layouts/partials/head.html
  layouts/partials/meta.html
  layouts/taxonomy/category.terms.html
Labels: bug, enhancement

#350 Update base code to fix hugo warnings
  layouts/partials/post/gallery.html
  layouts/partials/script.html
Labels: bug

#329 Correct some references of the orginial theme (Universal)
  README.md
  exampleSite/content/post/Welcome-to-the-new-Tranquilpeak.md
  layouts/partials/cover.html
Labels: bug, enhancement

#351 Upgrade dependencies and grunt task to support latest node engine
  .eslintrc
  .github/CONTRIBUTING.md
  docs/developer.md
  docs/user.md
  package-lock.json
  package.json
  src/js/about.js
  tasks/config/cssmin.js
  tasks/config/sails-linker.js
  tasks/config/sass.js
  tasks/config/uglify.js
  tasks/register/linkAssetsProd.js
  tasks/register/syncAssets.js
Labels: enhancement

#353 Cover img abs url
  CHANGELOG.md
  layouts/partials/post/header-cover.html
Labels: breaking changes, enhancement

#354 Remove search stuffs if algolia is not set
  layouts/partials/search.html
Labels: enhancement

#359 Remove stupid previous cover Image fix
  exampleSite/config.toml
  layouts/partials/post/header-cover.html
Labels: bug, documentation, enhancement

#358 Remove stupid previous cover Image fix
  exampleSite/config.toml
  layouts/partials/post/header-cover.html
Labels: bug, documentation, enhancement
