Repository kakawait/hugo-tranquilpeak-theme, pull requests merged in 2021-07, with the labels that each got.

#454 Typo fix
  docs/user.md
Labels: documentation

#450 Correct behaviour for Twitter cards
  layouts/partials/meta.html
Labels: bug

#376 Add link posts support
  layouts/_default/summary.html
Labels: enhancement

#366 Class on sidebar menu does not work
  docs/user.md
Labels: bug, documentation, waiting for feedback
