Repository kakawait/hugo-tranquilpeak-theme, pull requests merged in 2021-08, with the labels that each got.

#472 Update dependencies
  CHANGELOG.md
  docs/user.md
  exampleSite/config.toml
  exampleSite/content/posts/highlighted-code-showcase.md
  layouts/partials/head.html
  layouts/partials/script.html
  package-lock.json
  package.json
  src/scss/utils/_fonts.scss
  tasks/config/cssmin.js
  tasks/config/sails-linker.js
  tasks/config/uglify.js
Labels: enhancement, dependencies

#445 Implement looping over mainSections
  layouts/index.html
  layouts/partials/search.html
  layouts/taxonomy/archive.terms.html
  layouts/taxonomy/category.html
  layouts/taxonomy/category.terms.html
  layouts/taxonomy/tag.html
Labels: enhancement

#473 Add new shortcode toc to support new markup
  docs/user.md
  exampleSite/config.toml
  exampleSite/content/posts/Tags-plugins-showcase.md
  exampleSite/content/posts/Welcome-to-the-new-Tranquilpeak.md
  exampleSite/content/posts/highlighted-code-showcase.md
  layouts/_default/single.html
  layouts/shortcodes/toc.html
Labels: bug, breaking changes

#491 Fix reg from update to Fancybox 3.x.x
  layouts/partials/post/gallery.html
  layouts/shortcodes/image.html
Labels: bug
